
const $=(q,r=document)=>r.querySelector(q),$$=(q,r=document)=>[...r.querySelectorAll(q)];
function toast(m){let e=$('#toast');if(!e){e=document.createElement('div');e.id='toast';Object.assign(e.style,{position:'fixed',right:'18px',bottom:'18px',padding:'13px 16px',background:'#172033',color:'#fff',borderRadius:'12px',zIndex:'200',boxShadow:'0 12px 30px rgba(0,0,0,.18)',display:'none'});document.body.appendChild(e)}e.textContent=m;e.style.display='block';clearTimeout(window.__t);window.__t=setTimeout(()=>e.style.display='none',2600)}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
document.addEventListener('click',e=>{let o=e.target.closest('[data-open-modal]');if(o)$('#'+o.dataset.openModal)?.classList.add('open');let c=e.target.closest('[data-close-modal]');if(c)$('#'+c.dataset.closeModal)?.classList.remove('open');if(e.target.closest('[data-toggle-sidebar]'))$('#sidebar')?.classList.toggle('open');if(e.target.closest('[data-logout]')){localStorage.removeItem('studynest_user');location.href='index.html'}});
document.addEventListener('submit',e=>{if(e.target.matches('[data-demo-form]')){e.preventDefault();toast(e.target.dataset.success||'Saved successfully.');e.target.closest('.modal')?.classList.remove('open')}});
const u=JSON.parse(localStorage.getItem('studynest_user')||'null');$$('[data-user-name]').forEach(e=>e.textContent=u?.name||'Alex Rivera');
$('#loginForm')?.addEventListener('submit',e=>{e.preventDefault();let email=e.currentTarget.email.value.trim(),name=email.split('@')[0].replace(/[._-]/g,' ').replace(/\b\w/g,c=>c.toUpperCase());localStorage.setItem('studynest_user',JSON.stringify({name,email}));location.href='dashboard.html'});
$('#signupForm')?.addEventListener('submit',e=>{e.preventDefault();let name=e.currentTarget.name.value.trim(),email=e.currentTarget.email.value.trim();localStorage.setItem('studynest_user',JSON.stringify({name,email}));location.href='dashboard.html'});
function tasks(){return JSON.parse(localStorage.getItem('studynest_tasks')||JSON.stringify([{id:1,title:'Review biology chapter 4',date:'Today',done:false},{id:2,title:'Submit mathematics assignment',date:'Tomorrow',done:false},{id:3,title:'Read history notes',date:'Completed',done:true}]))}function saveTasks(x){localStorage.setItem('studynest_tasks',JSON.stringify(x))}function renderTasks(){let w=$('#taskList');if(!w)return;w.innerHTML=tasks().map(t=>`<div class="task ${t.done?'done':''}"><input type="checkbox" data-task-toggle="${t.id}" ${t.done?'checked':''}><div><strong class="task-title">${esc(t.title)}</strong><div class="task-date">${esc(t.date)}</div></div><button class="icon-btn" data-task-delete="${t.id}">×</button></div>`).join('')}
document.addEventListener('change',e=>{let b=e.target.closest('[data-task-toggle]');if(b){let x=tasks(),t=x.find(i=>String(i.id)===b.dataset.taskToggle);if(t)t.done=b.checked;saveTasks(x);renderTasks()}});document.addEventListener('click',e=>{let d=e.target.closest('[data-task-delete]');if(d){saveTasks(tasks().filter(t=>String(t.id)!==d.dataset.taskDelete));renderTasks();toast('Task removed.')}let n=e.target.closest('[data-note-delete]');if(n){saveNotes(notes().filter(x=>String(x.id)!==n.dataset.noteDelete));renderNotes();toast('Note deleted.')}});$('#taskForm')?.addEventListener('submit',e=>{e.preventDefault();let f=new FormData(e.currentTarget),x=tasks();x.unshift({id:Date.now(),title:f.get('title'),date:f.get('date')||'No due date',done:false});saveTasks(x);renderTasks();e.currentTarget.reset();e.currentTarget.closest('.modal').classList.remove('open');toast('Task added.')});renderTasks();
function notes(){return JSON.parse(localStorage.getItem('studynest_notes')||JSON.stringify([{id:1,title:'Biology: Cell Structure',body:'Key parts: nucleus, mitochondria, cytoplasm, membrane.'},{id:2,title:'History: Industrial Revolution',body:'Major changes in manufacturing, transportation, and society.'},{id:3,title:'Math: Quadratic Formula',body:'Use when a quadratic equation cannot be factored easily.'}]))}function saveNotes(x){localStorage.setItem('studynest_notes',JSON.stringify(x))}function renderNotes(){let w=$('#notesGrid');if(!w)return;w.innerHTML=notes().map(n=>`<article class="card note"><div class="panel-head"><h3>${esc(n.title)}</h3><button class="icon-btn" data-note-delete="${n.id}">×</button></div><p>${esc(n.body)}</p></article>`).join('')}$('#noteForm')?.addEventListener('submit',e=>{e.preventDefault();let f=new FormData(e.currentTarget),x=notes();x.unshift({id:Date.now(),title:f.get('title'),body:f.get('body')});saveNotes(x);renderNotes();e.currentTarget.reset();e.currentTarget.closest('.modal').classList.remove('open');toast('Note created.')});renderNotes();
